import ekosistemaSmeshanniiLes from '@/codgen/ekosistemaSmeshanniiLes';
import {LayerObjectType} from '@/components/interactive-parallax/layer-object';

export const sceneObjects: {[objName: string]: LayerObjectType} = {
    belka: {
        x: 30,
        y: 67.5,
        w: 7,
        src: ekosistemaSmeshanniiLes.zhivotnie.belka,
        isUnclickable: true,
        isHidden: true,
    },
    lisa: {
        x: 30,
        y: 67.5,
        w: 7,
        src: ekosistemaSmeshanniiLes.zhivotnie.lisa,
        isUnclickable: true,
        isHidden: true,
    },
    volk: {
        x: 30,
        y: 67.5,
        w: 7,
        src: ekosistemaSmeshanniiLes.zhivotnie.volk,
        isUnclickable: true,
        isHidden: true,
    },
    lyagushka: {
        x: 30,
        y: 67.5,
        w: 7,
        src: ekosistemaSmeshanniiLes.zhivotnie.lyagushka,
        isUnclickable: true,
        isHidden: true,
    },
    zmeya: {
        x: 30,
        y: 67.5,
        w: 7,
        src: ekosistemaSmeshanniiLes.zhivotnie.zmeya,
        isUnclickable: true,
        isHidden: true,
    },
    zayats: {
        x: 30,
        y: 67.5,
        w: 7,
        src: ekosistemaSmeshanniiLes.zhivotnie.zayats,
        isUnclickable: true,
        isHidden: true,
    },
    grib: {
        x: 30,
        y: 67.5,
        w: 7,
        src: ekosistemaSmeshanniiLes.rasteniya.grib,
        isUnclickable: true,
        isHidden: true,
    },
    trava1: {
        x: 30,
        y: 67.5,
        w: 7,
        src: ekosistemaSmeshanniiLes.rasteniya.trava1,
        isUnclickable: true,
        isHidden: true,
    },
    trava2: {
        x: 30,
        y: 67.5,
        w: 7,
        src: ekosistemaSmeshanniiLes.rasteniya.trava2,
        isUnclickable: true,
        isHidden: true,
    },
};
